// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvEYKYymh6MMra2x8vfLbXJLOvQpaBUtA',
    appId: '1:211115135732:web:b6a7818c3a853f2c6444a1',
    messagingSenderId: '211115135732',
    projectId: 'thawaf-adf26',
    authDomain: 'thawaf-adf26.firebaseapp.com',
    storageBucket: 'thawaf-adf26.firebasestorage.app',
    measurementId: 'G-L2D8NGS4RX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-bFgYnIcOnQKxrcsM6QSSRvXHCPsVyfc',
    appId: '1:211115135732:android:e188e2be8749c0b56444a1',
    messagingSenderId: '211115135732',
    projectId: 'thawaf-adf26',
    storageBucket: 'thawaf-adf26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmld-NEqzwrP5zRSGgqd23tFl7LNNTIIM',
    appId: '1:211115135732:ios:596e984f360ee8226444a1',
    messagingSenderId: '211115135732',
    projectId: 'thawaf-adf26',
    storageBucket: 'thawaf-adf26.firebasestorage.app',
    iosBundleId: 'com.example.hehehe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmld-NEqzwrP5zRSGgqd23tFl7LNNTIIM',
    appId: '1:211115135732:ios:596e984f360ee8226444a1',
    messagingSenderId: '211115135732',
    projectId: 'thawaf-adf26',
    storageBucket: 'thawaf-adf26.firebasestorage.app',
    iosBundleId: 'com.example.hehehe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvEYKYymh6MMra2x8vfLbXJLOvQpaBUtA',
    appId: '1:211115135732:web:8ad8f3acc76d72a66444a1',
    messagingSenderId: '211115135732',
    projectId: 'thawaf-adf26',
    authDomain: 'thawaf-adf26.firebaseapp.com',
    storageBucket: 'thawaf-adf26.firebasestorage.app',
    measurementId: 'G-L3SENT21RH',
  );
}
